# Site settings

title: Grain Growth
header-img: img/grain-growth.png
email: fredhohman@gatech.edu
description: "Grain Growth Project for CSE 8803/ME 8883 at Georgia Tech."
baseurl: "/grain-growth"
url: "http://Materials-Informatics-Class-Fall2015.github.io"
github_username:  fredhohman
project_repository: MIC-grain-growth
disqus_shortname: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
